### ISSUE TITLE
Silverfish Crash with Onslaught

### ISSUE THREAD

**Issue by mxnmnm** [FatherToast/SpecialMobs#16]
I was testing onslaught raids and I crashed 

https://gist.github.com/mxnmnm/5e63f77700636b5265fcb36bc06e9d3d

It blames silverfish, which I am spawning in, does it not like me giving them custom ais using onslaught?

**Comment by FatherToast** [comment]
This one might be caused by the "aggressive silverfish" option.  Disabling that might prevent the crash.  Otherwise, I'm not sure of the root cause since comod exceptions are difficult to diagnose.

**Comment by mxnmnm** [comment]
The issue seemed to be whenever I used onslaught's teleport ai with the silverfish.
