### ISSUE TITLE
specialmobs:skeleton-crash

### ISSUE THREAD

**Issue by ghost** [FatherToast/SpecialMobs#20]
[crash-2022-09-16_21.35.20-server.txt](https://github.com/FatherToast/SpecialMobs/files/9584489/crash-2022-09-16_21.35.20-server.txt)
1.16.5
forge36.2.39

**Comment by FanRenLa** [comment]
I just played mobs at night and placed a lot of (Iron Golem) to help me, other than that, there seems to be nothing abnormal, (Epic Fight) changed the original creature action, maybe it's related.

**Comment by FanRenLa** [comment]
Vampirism, I don't seem to interfere with it

**Comment by FatherToast** [comment]
The NPE is happening very deep in the base skeleton code, so I am thinking the cause is likely something other than Special Mobs.  The most suspicious things I saw in the crash report are "pl:mixin:APP:brutalbosses.mixins.json:MeleeAttackGoalMixin" and "pl:mixin:APP:enhancedai.mixins.json:AbstractSkeletonEntityMixin".  There are also a lot of other mixins on the base classes, so it's hard to say what is directly causing the issue, but my first guess would say to look at brutalbossesmce-1.2 or EnhancedAI-1.2.3-mc1.16.5.

**Comment by FanRenLa** [comment]
I've used those two before, so I don't want to doubt it!

**Comment by FanRenLa** [comment]
Because before, 1.12.2, I used your mod and it crashed directly, so I directly suspected your mod,

**Comment by FatherToast** [comment]
Yes, it could be something with the way Special Mobs handles AI and equipment.

However, fixing it from my side would pretty much just involve implementing my own melee attack AI, which would unfortunately disable whatever changes Enhanced AI is making to it.

**Comment by FanRenLa** [comment]
In fact, it does not seem to be a big problem if it is not repaired. It seems that no one except me has added these mods at the same time. For unnecessary trouble, unless someone still reports an error, it feels that there is no need to repair it.

**Comment by FanRenLa** [comment]
The best way is, I only keep your SpecialMobs

**Comment by FanRenLa** [comment]
did you fix it

**Comment by FatherToast** [comment]
In the recent minor update, no - I don't have any way to fix this aside from removing compatibility with things.  I am leaving this issue open for now so we don't lose track of it.  If it is definitely narrowed down to Brutal Bosses - Dungeon Bosses, we can try and work with them on it.  However, if the crash is very difficult to reproduce (I don't know right now how frequent the crash is), it might be hard to narrow it down.

**Comment by Sarinsa** [comment]
I'll investigate the issue a bit, but I expect the root cause to be Brutal Bosses like toast said. We can track down the problematic code and send them a pull request, but it depends on whether or not the author wishes to update the 1.16.5 version of the mod

**Comment by Sarinsa** [comment]
What version of the mods Brutal Bosses, Enhanced AI and Epic Fight did you use?

**Comment by FanRenLa** [comment]
EnhancedAI-1.2.3-mc1.16.5，Brutal Bosses4.7,EpicFight-16.6.1;(EpicFight-16.6.1) Update today (EpicFight-16.6.2).

**Comment by Sarinsa** [comment]
So far I have not been able to reproduce the crash. It may have happened under a very specific condition, or there may be another underlying mod that has not been mentioned that causes it together with the other mods. Problems like these often happen in larger modpacks where it is hard to pinpoint what mods exactly are problematic, cause it could be multiple. If you still want to get to the root of the crash, I think the best way to go about it would be to play with Special Mobs alone, then add the other mods gradually to maybe get a better clue. This is tedious though!

**Comment by FanRenLa** [comment]
（improvedmobs-1.16.5-1.10.13）（spiders-2.0-1.16.4-1.0.4）（roughmobsrevamped-1.16.5-0.0.3）What about these?

**Comment by FanRenLa** [comment]
> 到目前为止，我还无法重现崩溃。它可能是在非常特定的条件下发生的，或者可能有另一个未提及的基础模块与其他模块一起导致它。此类问题经常发生在较大的模组包中，很难确定哪些模组确实存在问题，因为它可能是多个。如果您仍然想找到崩溃的根源，我认为最好的方法是单独玩特殊小怪，然后逐渐添加其他模组以获得更好的线索。虽然这很乏味！

(lycanitesmobs-1.16.5-2.3.3.3)(improvedmobs-1.16.5-1.10.13)(spiders-2.0-1.16.4-1.0.4)(roughmobsrevamped-1.16.5-0.0.3)
What about these?

**Comment by Sarinsa** [comment]
No longer maintaining 1.16.5
