### ISSUE TITLE
(1.16.5) Zombie from Special Mobs causes crash when touching the spikes of the spike trap from Wesley's Roguelike Dungeons.

### ISSUE THREAD

**Issue by SpecialtyK** [FatherToast/SpecialMobs#21]
Issue: <java.lang.NullPointerException: Colliding entity with block. Crash report: https://paste.ee/p/yZxLC#s=0>

Version: <Wesley's Roguelike Dungeons (Version 1.0).jar with specialmobs-1.16.5-1.0.1.jar

 

Issue description:

<When a mob from Special Mobs (specialmobs-1.16.5-1.0.1.jar) touches the spike trap while the spikes are out it causes a crash. I tried a piglin and a zombie. Other modded creatures seem to work as intended though. Posted issue on both mod pages>

 

How to reproduce:

<Place spike trap from Wesley's Roguelike Dungeons, activate trap, summon special mobs mod on trap, server crash.>

**Comment by FatherToast** [comment]
Seems like the spike block is giving a null block state.  That is bound to cause crashes like this; for example, vanilla spiders.

**Comment by SpecialtyK** [comment]
I did further testing with Special Mobs disabled and no mobs seem to be causing crashes when hurt by the spike trap.  Vanilla spiders,  vanilla cave spiders, and several spiders from other mods, however, are not hurt by the traps at all. I also tested several other vanilla mobs and various modded mobs and they all seem to work as intended, taking damage with no crash.

**Comment by Sarinsa** [comment]
It is fixable on our side, but that would only make it not crash with Special Mobs. It would be better if the author of WRD fixed it on their end so it doesn't explode other mods

**Comment by FatherToast** [comment]
> It is fixable on our side, but that would only make it not crash with Special Mobs. It would be better if the author of WRD fixed it on their end so it doesn't explode other mods

Exactly, plus it would allow them to let the block damage spiders, which I am assuming were disabled due to crashing.  If the mod author is unsure how to fix, I'm sure either of us would be happy to help.

**Comment by SpecialtyK** [comment]
Thank you for your time and quick responses. I will pass this information along to the other mod author and hopefully this can get resolved.

**Comment by Sarinsa** [comment]
Assuming the author of WRD may not be actively developing the 1.16.5 version of the mod anymore, we have fixed it on our end
