### ISSUE TITLE
incompatible with Cracker's Wither Storm Mod

### ISSUE THREAD

**Issue by Kasualix** [FatherToast/SpecialMobs#23]
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/713

Crash report: https://pastebin.ubuntu.com/p/vXh5rjQMvF/

**Comment by Sarinsa** [comment]
Could you provide some more info on this? Forge version, SpecialMobs version, WSM version etc. Were you doing anything specific when it happened?

**Comment by CatastropheChou** [comment]
witherstormmod 1.0.2.4
special mobs 1.0.2
forge 36.2.39
I installed specialmobs, launched the game, entered the world, summoned an Abyssal Drowned, looked at it, and the game just crashed all of a sudden

**Comment by Sarinsa** [comment]
No longer maintaining 1.16.5
