### ISSUE TITLE
Missing entity type tags

### ISSUE THREAD

**Issue by Mechalopa** [FatherToast/SpecialMobs#24]
Entities are not registered in `minecraft:impact_projectiles`, `minecraft:raiders`, and `minecraft:skeletons` tags.

**Comment by Sarinsa** [comment]
Ah shoot! Forgot about tags. Thanks for the heads up!

**Comment by Sarinsa** [comment]
It has now been taken care of! The patch will be included in the next update, not sure exactly when that will be though
