### ISSUE TITLE
1.16.5 CLient render crash

### ISSUE THREAD

**Issue by ShootToKillSTK** [FatherToast/SpecialMobs#25]
Not sure why /whats happening but I keep crashing while on my server, but server doesn't crash
[crash-2022-11-03_19.53.18-client.txt](https://github.com/FatherToast/SpecialMobs/files/9934076/crash-2022-11-03_19.53.18-client.txt)

**Comment by Sarinsa** [comment]
No longer maintaining 1.16.5
