### ISSUE TITLE
[1.16.5] Skeleton Creeper's Bone Shrapnel cause crash when hitting any entity

### ISSUE THREAD

**Issue by Colin-J-Wood** [FatherToast/SpecialMobs#26]
Conflict with Parrying mod

[crash-2022-12-20_18.40.55-server.txt](https://github.com/FatherToast/SpecialMobs/files/10271252/crash-2022-12-20_18.40.55-server.txt)

**Comment by FatherToast** [comment]
I recommend posting this on the other mod's page.  I can't see any link to Special Mobs in the crash report, so I don't have any idea what could be causing it on my end.

**Comment by Colin-J-Wood** [comment]
As I mentioned in the pull request, the issue is because you are trying to set health instead of using a hurt event.  Parrying breaks whenever a mod sets health directly instead of relying on the hurt/heal methods.

**Comment by Sarinsa** [comment]
Will take a look at this later today if possible

**Comment by FatherToast** [comment]
Bone shrapnel doesn't do that, it's just a reskinned arrow that despawns faster.
