### ISSUE TITLE
[1.16.5] Cannot disable a species' spawn via general.natural_spawn_chance.base 0.0

### ISSUE THREAD

**Issue by Colin-J-Wood** [FatherToast/SpecialMobs#27]
Can only disable a spawn via setting the specific mob's weight to 0 in the corresponding family json.

**Comment by FatherToast** [comment]
Can you describe exactly what is happening?  Please note these are two different spawn methods that should not interact.

**Comment by Colin-J-Wood** [comment]
I'm trying to disable the spawn of Skeleton Creepers in hopes to prevent the crash caused by #26 but everywhere in the config that is specific to the species, nothing works.  the Skeleton Creeper will still spawn.  Setting the weight to 0 "helps", but now he just seems to show up rarely instead of impossibly.

**Comment by FatherToast** [comment]
You could apply a 0x health multiplier in the species file for now, should instantly cause any spawns to die.  I'll look into the weighting thing.

**Comment by Sarinsa** [comment]
No longer maintaining 1.16.5
