### ISSUE TITLE
[1.16.5] Dungeons Mobs/Dungeons Libraries breaks config

### ISSUE THREAD

**Issue by Sazuzaki** [FatherToast/SpecialMobs#31]
Dungeons Mobs/Library breaks the option to tweak attribute modifiers. Basically, I can't edit max health or damage with it installed.

**Comment by FatherToast** [comment]
I don't think there's anything I can do about this.  Try forcing SM to load after the mods that break it, maybe it'll work then.  I recommend posting a bug report on their page and paste a link here so I can follow/help.

**Comment by Sazuzaki** [comment]
> I don't think there's anything I can do about this. Try forcing SM to load after the mods that break it, maybe it'll work then. I recommend posting a bug report on their page and paste a link here so I can follow/help.

Will do, and thanks for suggesting a fix. Really love this mod, so it sucks these two have trouble working together. I've been making do with the MobsPropertiesRandomness mod for modifying attributes, but it's just been... lets just say painful making a new file for every single mob.

Good luck and hope to see more for you!

**Comment by Sarinsa** [comment]
No longer maintaining 1.16.5
