### ISSUE TITLE
Error 1.16.5 ModPack

### ISSUE THREAD

**Issue by LolhaxOmega** [FatherToast/SpecialMobs#33]
When I use this mod, it always happens to me that in some places in my worlds everything stops working, mobs do not react, blocks do not drop items and no more fragments are generated. (use Google translate)

**Comment by Sarinsa** [comment]
Do you crash or get any error logs at all, or does the server just hang up completely?

**Comment by Sarinsa** [comment]
No longer maintaining 1.16.5
