### ISSUE TITLE
SpecialMobs v3.1.2 Special Skeletons & Special Wither Skeletons Texture Issue.

### ISSUE THREAD

**Issue by GrandeMalum** [FatherToast/SpecialMobs#36]
Hello. I want to report an issue with the latest available SpecialMobs mod version (v3.1.2). I've noticed, that some special skeletons and special wither skeletons textures are broken after mod moved on to Minecraft 1.20.1. The skeletons lost their outer texture layer, like clothes, fangs and other 3D accessory. The best example of the issue are the strays. Just compare vanilla strays to special strays and you'll easily notice the issue.

<img width="510" alt="2" src="https://github.com/FatherToast/SpecialMobs/assets/6556646/ba79b867-3987-43ea-a787-1b7fdadd8d5d">

![image](https://github.com/FatherToast/SpecialMobs/assets/6556646/3467d7a1-3fde-43a8-9142-8bb928844457)

And here is a poison skeleton, just in case. You can see the outer texture layer is gone.
![image](https://github.com/FatherToast/SpecialMobs/assets/6556646/4cb28a29-ea19-4597-95ee-5c5ffab7227f)

**Comment by Sarinsa** [comment]
Fixed
