### ISSUE TITLE
[1.20.1] World Generation Crash

### ISSUE THREAD

**Issue by MCKuma** [FatherToast/SpecialMobs#41]
MC Version: 1.20.1

Mod Version: 3.1.4

I've experience that the Mod unfortunately on two different modpacks can cause chunks to not load and the game to overstress and freeze during generation, no crash log or nothing mentioned in logs. Figured it out by taking mods out one at a time and reloading copies of the same world where it always crashes.  Can't find a direct incompatibility either cause they do generally work. Happens on Lan and in Singleplayer in random chunks that attempt generation. Sorry if this doesn't help, let me know if you need anything else.

[latest.log](https://github.com/user-attachments/files/16203861/latest.log)

**Comment by Sarinsa** [comment]
Sadly there is not much information to go off of here.  Perhaps try removing the mod "Dungeons Arise". If you no longer crash after doing that, we at least have some clue as to what might be going on

**Comment by MCKuma** [comment]
I have a world where I can recreate this, on attemping to remove Dungeons Arise + Dungeons Arise:Seven Seas the world still froze in the same place. My other modpack that had this issue is smaller, I'll cross reference what mods both has and try to find a incompatibility.

**Comment by MCKuma** [comment]
Can confirm the incompatibility is with the Canary mod, upon removal of either mod, the world will continue loading and not freeze, but not with both on at once.

**Comment by Sulferix** [comment]
can confirm this exact issue occurs on the latest 1.16.5 version as well. absolutely awful error. zero logs or information.

**Comment by Sarinsa** [comment]
We now know what causes this problem, and a fix has been provided in the newest 1.16.5 version. We are rolling out a fix for 1.20.1 soon as well, wahoo!

**Comment by Sulferix** [comment]
the new update did improve things, but only slightly. the game still freezes when loading a world, it just gets slightly past the spawn chunk generation phase. 
[latest.log](https://github.com/user-attachments/files/16739039/latest.log)

**Comment by Sarinsa** [comment]
I see you have a lot of different mods installed. It is hard to tell with what mod the incompatibility lies, but given that it is still a deadlock and not a crash makes me raise an eyebrow. You are on 1.16.5, correct?

**Comment by Sulferix** [comment]
yes correct. its notable that the artifacts mod has the same issue. it is independent from this mod. both of these mods will individually deadlock the game on load.
