### ISSUE TITLE
[1.20.1] Mob Config not working

### ISSUE THREAD

**Issue by dieflemm** [FatherToast/SpecialMobs#42]
It seems like the mob config options dont affect the mobs and all special mobs have the same health.

Example
 general.attributes = [
    "minecraft:generic.max_health + 20.0",
    "minecraft:generic.attack_damage + 5.0"
  ]

MC1.20.1 SpecialMobs 3.1.4

**Comment by FatherToast** [comment]
This has been fixed at some point (not sure when exactly).  If you still have issues in 3.1.5, please (re)open the issue.
