### ISSUE TITLE
Game crashes on launch

### ISSUE THREAD

**Issue by wsxiya** [FatherToast/SpecialMobs#44]
When used with Physics Mod, the game will crash when launched. Please make it compatible with Physics Mod

**Comment by wsxiya** [comment]
minecraft v1.20.1 forge 47.3.5 Special Mobs.20.1-3.1.4

**Comment by Sarinsa** [comment]
Without a crash log there isn't much I can do about this

**Comment by wsxiya** [comment]
> 如果没有崩溃日志，我对此无能为力

You only need to install these three mods
Physics Mod
Crust
Special Mobs
, the game will crash when you start it, and you can get the crash log

**Comment by Sarinsa** [comment]
to be clear, is this the item physics mod you are talking about?

**Comment by wsxiya** [comment]
> 如果没有崩溃日志，我对此无能为力

I just created a crash log
[错误报告-2024-8-9_7.54.59.zip](https://github.com/user-attachments/files/16554236/-2024-8-9_7.54.59.zip)

**Comment by wsxiya** [comment]
> 需要明确的是，这是你说的 Item Physics Mod 吗？

Yes, this is my mod list
![TP79KH$0R6UQJW3JUO$90)0](https://github.com/user-attachments/assets/ed033af5-c834-45c2-83fc-f347a4b40067)

**Comment by Sarinsa** [comment]
Identified the bug already, I'll try and provide a patch next update

**Comment by Sarinsa** [comment]
Note to self: BlazeMixin is out-prioritized by Physic's. Make ours fail safely

**Comment by Gavin456b** [comment]
+1 for this same issue

**Comment by wsxiya** [comment]
Hello, I just saw that 1.20.1 has been updated, but it seems that the crash problem has not been fixed.

**Comment by Sarinsa** [comment]
Hm, can you send the most recent log?

**Comment by wsxiya** [comment]
> 嗯，你能发送最新的日志吗？

[latest.log](https://github.com/user-attachments/files/16760768/latest.log)

**Comment by Sarinsa** [comment]
Unlike last time it looks like our mixin is getting skipped as intended instead of crashing, so something else must be causing this. Do you have a more detailed debug log you can send or is that all it says?

**Comment by wsxiya** [comment]
> 与上次不同的是，我们的 mixin 似乎按预期被跳过而不是崩溃，所以一定是其他原因导致了这种情况。您是否有更详细的调试日志可以发送，或者它只是说的吗？

I only installed the three mods I tested before, without any additional mods. I believe you can easily reproduce the crash and get more detailed logs

**Comment by Sarinsa** [comment]
It appears I completely misunderstood something important! A hotfix will be released in a couple minutes

**Comment by Gavin456b** [comment]
Thanks for this!
