### ISSUE TITLE
Texture bug

### ISSUE THREAD

**Issue by AmazingPyro** [FatherToast/SpecialMobs#47]
The textures bug with the mods EMF (https://www.curseforge.com/minecraft/mc-mods/entity-model-features) and ETF (https://www.curseforge.com/minecraft/mc-mods/entity-texture-features-fabric)

**Comment by Sarinsa** [comment]
The mobs in SM uses custom renderers and models, which includes the vanilla replacement mobs. Writing compatibility for this is likely not going to be a priority, sorry about that
