### ISSUE TITLE
Server crash 1.20.1 3.1.6

### ISSUE THREAD

**Issue by 4N3v3r** [FatherToast/SpecialMobs#50]
Server crash bc of Special Mobs i don't really get why it's happends randomly while chank loading. Crash report:
[message (1).txt](https://github.com/user-attachments/files/17021366/message.1.txt)

Theres mod list (html converted to txt):
[modlist.txt](https://github.com/user-attachments/files/17021387/modlist.txt)

and just names of mods:
[Modlist (2).txt](https://github.com/user-attachments/files/17021397/Modlist.2.txt)

I would be gratefull for some help

**Comment by Sarinsa** [comment]
Try removing Canary and see if the issue persists

**Comment by FatherToast** [comment]
Epic Fight Mod has had issues with SM in the past, not sure if it still does.

**Comment by FatherToast** [comment]
That particular one might just be a weird edge case where something causes a loaded chunk to be unloaded before the end of the same tick.  Should be fixable on our end.

**Comment by Sarinsa** [comment]
@mateus3c @4N3v3r If possible, hit me up on Discord. I'd like to toss you a test jar to see if the problem persists with the new change

**Comment by Sarinsa** [comment]
just sarinsa, same as here :)

**Comment by Sarinsa** [comment]
Should be fixed in most recent version
