### ISSUE TITLE
Mob Replacer is not safe against chunks unloading mid-replace

### ISSUE THREAD

**Issue by FatherToast** [FatherToast/SpecialMobs#51]
https://mclo.gs/JuXLT6b - any idea what could be causing the crash?

_Originally posted by @mateus3c in https://github.com/FatherToast/SpecialMobs/issues/50#issuecomment-2366904971_
            
Note: It appears a loaded chunk could be unloaded before the tick end.

**Comment by Sarinsa** [comment]
Fixed 🕺
