### ISSUE TITLE
Constant spam in server console

### ISSUE THREAD

**Issue by tjsd** [FatherToast/SpecialMobs#7]
Pack: Dungeon, Dragons and Space Shuttles
Forge: 2815
Special Mobs: specialmobs-1.0.2_for_mc1.12.2.jar

The error:

> [Server thread/ERROR] [FML]: FMLIndexedMessageCodec exception caught
> io.netty.handler.codec.EncoderException: java.lang.RuntimeException: Undefined discriminator for message type fathertoast.specialmobs.MessageTexture in channel SM|FX
>         at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:106) ~[minecraft_server.1.12.2.jar:?]
>         at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[minecraft_server.1.12.2.jar:?]
>         at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[minecraft_server.1.12.2.jar:?]
>         at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[minecraft_server.1.12.2.jar:?]
>         at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[minecraft_server.1.12.2.jar:?]
>         at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[minecraft_server.1.12.2.jar:?]
>         at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[minecraft_server.1.12.2.jar:?]
>         at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[minecraft_server.1.12.2.jar:?]
>         at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[minecraft_server.1.12.2.jar:?]
>         at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendToDimension(SimpleNetworkWrapper.java:309) [SimpleNetworkWrapper.class:?]
>         at fathertoast.specialmobs.entity.SpecialMobData.onUpdate(SpecialMobData.java:208) [SpecialMobData.class:?]
>         at fathertoast.specialmobs.entity.skeleton.Entity_SpecialSkeleton.onLivingUpdate(Entity_SpecialSkeleton.java:282) [Entity_SpecialSkeleton.class:?]
>         at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2179) [vp.class:?]
>         at net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:295) [vq.class:?]
>         at net.minecraft.entity.monster.EntityMob.onUpdate(EntityMob.java:50) [ade.class:?]
>         at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1993) [amu.class:?]
>         at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832) [oo.class:?]
>         at net.minecraft.world.World.updateEntity(World.java:1955) [amu.class:?]
>         at net.minecraft.world.World.redirect$updateEntity$zzp000(World.java:5117) [amu.class:?]
>         at net.minecraft.world.World.updateEntities(World.java:1759) [amu.class:?]
>         at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613) [oo.class:?]
>         at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767) [MinecraftServer.class:?]
>         at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) [nz.class:?]
>         at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
>         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
>         at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
> Caused by: java.lang.RuntimeException: Undefined discriminator for message type fathertoast.specialmobs.MessageTexture in channel SM|FX
>         at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:76) ~[FMLIndexedMessageToMessageCodec.class:?]
>         at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[minecraft_server.1.12.2.jar:?]
>         at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88) ~[minecraft_server.1.12.2.jar:?]
>         ... 25 more

**Comment by xxlio109** [comment]
me too
